-- local avante = require('avante')
-- local config = {
--   providers = {
--     claude = {
--       endpoint = "https://api.anthropic.com",
--       model = "claude-sonnet-4-20250514",
--       timeout = 30000,    -- Timeout in milliseconds
--       disable_tools = true, -- disable tools!
--       extra_request_body = {
--         temperature = 0.75,
--         max_tokens = 4096,
--       }
--     }
--   }
-- }
-- avante.setup(config)
