-- require("codecompanion").setup({
--   extensions = {
--     opts = {
--       make_vars = true,
--       make_slash_commands = true,
--       strategies = {
--         chat = {
--           adapter = "gemini",
--         },
--         inline = {
--           adapter = "gemini",
--         },
--       },
--       gemini = function()
--         return require("codecompanion.adapters").extend("gemini", {
--           schema = {
--             model = {
--               default = "gemini-2.5-flash-preview-05-20"
--             },
--           },
--           env = {
--             api_key = "GEMINI_API_KEY",
--           },
--         })
--       end,
--       display = {
--         diff = {
--           provider = "mini_diff",
--         },
--       },
--     },
--     show_result_in_chat = true
--   }
-- })
