-- local opts = { noremap = true, silent = true }
-- vim.api.nvim_set_keymap("n", "<leader>n", "<cmd>RnvimrToggle<CR>", opts)

-- vim.g.rnvimr_enable_picker = 1
-- vim.g.rnvimr_enable_bw = 1
-- vim.g.rnvimr_edit_cmd = 'drop'
-- vim.g.rnvimr_vanilla = 1
-- vim.g.rnvimr_layout = {
--     relative = 'editor',
--     width = vim.fn.float2nr(vim.fn.round(0.6 * 500)),
--     height = vim.fn.float2nr(vim.fn.round(0.6 * 500)),
--     col = vim.fn.float2nr(vim.fn.round(0.2 * 500)),
--     row = vim.fn.float2nr(vim.fn.round(0.2 * 500)),
--     style = 'minimal'
-- }
